sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t betelgeitze/blutspender -f ./app/Dockerfile ./app

#script:
#  - docker run -e CI=true betelgeitze/blutspender

after_success:
  - docker build -t betelgeitze/blutspender ./app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push betelgeitze/blutspender