sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t betelgeitze/blutspender -f ./app/Dockerfile ./app

#script:
#  - docker run -e CI=true betelgeitze/blutspender

after_success:
  - docker build -t betelgeitze/blutspender ./app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push betelgeitze/blutspender

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-771077539328'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY