sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t betelgeitze/blutspender-test -f ./app/Dockerfile.dev ./app

script:
  - docker run -e CI=true betelgeitze/blutspender-test

after_success:
  - docker build -t betelgeitze/blutspender ./app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push betelgeitze/blutspender