sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t betelgeitze/blutspender -f ./bot/Dockerfile-parser-bot ./bot #TODO: WRONG REWRITE IT

#script:
#  - docker run -e CI=true betelgeitze/blutspender

after_success:
  - docker build -t betelgeitze/blutspender ./bot
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push betelgeitze/blutspender

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'blutspender'
  env: 'Blutspender-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-771077539328'
  bucket_path: 'blutspender'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY