version: '3'
services:
  blutspender:
    image: 'betelgeitze/blutspender'
    mem_limit: 128m
    hostname: blutspender
    environment:
      - BOT_API_KEY=$BOT_API_KEY
      - POSTGRES_DB=$POSTGRES_DB
      - HOSTNAME=$HOSTNAME
      - PORT_ID=$PORT_ID
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER