version: '3'
services:
  bot:
    image: 'betelgeitze/bot'
    mem_limit: 128m
    restart: always
    depends_on:
      - parser
    hostname: bot
    environment:
      - BOT_API_KEY=$BOT_API_KEY
      - POSTGRES_DB=$POSTGRES_DB
      - HOSTNAME=$HOSTNAME
      - PORT_ID=$PORT_ID
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
  parser:
    image: 'betelgeitze/parser'
    mem_limit: 128m
    restart: always
    hostname: parser
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - HOSTNAME=$HOSTNAME
      - PORT_ID=$PORT_ID
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER