version: '3'
services:
  blutspender:
    env_file: ./.env
    build:
      dockerfile: Dockerfile.dev
      context: ./app
  database:
    image: 'postgres:latest'
    env_file: ./.env
    restart:
      always
    #    ports:
    #      - 5432:5432
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8080:8080