version: '3'
services:
  blutspender:
    env_file: ./.env
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    depends_on:
      - database
    # Somehow my volumes do not work how I wished they would. If the container runs and I change smth in python scripts,
    # the changes are not reflected real time and I have to rerun docker-compose up command to see changes :(
    volumes:
      - ./app:/blutspender
  database:
    image: 'postgres:latest'
    env_file: ./.env
    ports:
      - 5432:5432
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8080:8080