version: '3'
services:
  bot:
    image: 'betelgeitze/bot'
    env_file: ./.env
    depends_on:
      - database
#  parser:
#    image: 'betelgeitze/parser'
#    env_file: ./.env
#    depends_on:
#      - database
#  sender:
#    image: 'betelgeitze/sender'
#    env_file: ./.env
#    depends_on:
#      - database
  database:
    image: 'postgres:latest'
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8080:8080